### ISSUE TITLE
Running with --no-xvfb flag causes NoMethodError

### ISSUE THREAD

**Issue by coliver** [roberts1000/rspec_starter#49]
```bash
/rspec_starter-1.4.0/lib/rspec_starter/steps/prepare_database_step.rb:50:in `successful?': undefined method `exitstatus' for nil:NilClass (NoMethodError)
```
This is happening [here](https://github.com/roberts1000/rspec_starter/blob/master/lib/rspec_starter/steps/prepare_database_step.rb#L50) because running rspec_starter without xvfb causes $CHILD_STATUS to be nil.

**Comment by roberts1000** [comment]
Hi.  I didn't have notifications turned on for this repo so I'm just seeing this. :(   I think this is no longer an issue (due to the enhancement I made for #51).  If it's still a problem, let me know and we'll get your PR merged.

**Comment by coliver** [comment]
Hey @roberts1000, after updating to 1.5.0, running start_rspec with --no-xvfb now gives:

```
$ bin/start_rspec --no-xvfb --only-failures
[1] Preparing the test database with 'rake db:drop db:create db:migrate RAILS_ENV=test' ... Success
[2] Removing tmp folder ... Success!!
[3] Running specs with 'bundle exec rspec --no-xvfb --only-failures' ...

invalid option: --no-xvfb

Please use --help for a listing of valid options
```

Looking at --help, it says --no-xvfb is still an option:

```
$ bin/start_rspec --help
Usage: /home/vagrant/.rvm/gems/ruby-2.5.3/gems/.../rspec_starter.rb [options] [options for RSpec]
       /home/vagrant/.rvm/gems/ruby-2.5.3/gems/.../rspec_starter.rb will look for its own options first then pass any remaining options to rspec

Options: (run 'rspec --help' to see RSpec's options)
       --no-xvfb   DO NOT run XVFB (this can speed up RSpec when running tests that don't need XVFB)
       --no-prep   DO NOT prepare the test database (can speed up testing if you know the DB is clean)

Examples:
       /home/vagrant/.rvm/gems/ruby-2.5.3/gems/.../rspec_starter.rb spec/features (only run specs in the specs/features folder)
       /home/vagrant/.rvm/gems/ruby-2.5.3/gems/.../rspec_starter.rb spec/features/some_spec:53 (run the spec on line 53 of the spec/features_some_spec.rb file)
       /home/vagrant/.rvm/gems/ruby-2.5.3/gems/.../rspec_starter.rb --no-xvfb spec/requests/some_spec (don't start XVFB since it's not needed for request specs)
       SIMPLECOV_FORMATTER=rcov /home/vagrant/.rvm/gems/ruby-2.5.3/gems/.../rspec_starter.rb (use with environment variables)
```

**Comment by roberts1000** [comment]
Thanks @coliver.   I'm almost finished rewriting the entire internals of the gem.  I'll have this solved in the new release.

**Comment by roberts1000** [comment]
This was fixed by https://github.com/roberts1000/rspec_starter/pull/68
